name: Translations

on:
  push:
    paths:
      - '.github/workflows/translations.yml'
      - 'translation/**'
      - 'bin/trans-lint'
      - 'ui/.build/src/i18n.ts'
  pull_request:
    paths:
      - '.github/workflows/translations.yml'
      - 'translation/**'
      - 'bin/trans-lint'
      - 'ui/.build/src/i18n.ts'

jobs:
  xmllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils
      - name: Validate translation files
        run: xmllint --noout --dtdvalid translation/resources.dtd translation/**/*.xml

  trans-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Lint translation files
        run: ./bin/trans-lint translation/dest/*/*.xml

  i18n-key-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
      - run: pnpm install
      - run: pnpm i18n-file-gen
      - run: ./ui/build --i18n
      - name: i18n files up-to-date check
        run: |
          git status --porcelain
          git diff
          if [[ -n $(git status --porcelain) ]]; then
              echo "i18n files are out of date. Please run `pnpm i18n-file-gen` and `./ui/build --i18n` and commit the changes.";
              exit 1;
          fi

  dests-unmodified-check:
    runs-on: ubuntu-latest
    #if: github.event_name == 'pull_request' && github.event.pull_request.title != 'New Crowdin updates'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - name: Get modified files
        id: modified_files
        run: |
          files=$(gh pr diff ${{ github.event.pull_request.number }} --name-only)
          echo $files
          echo "::set-output name=files::$files"
      - name: Destination translation files are unmodified
        run: |
          exit_code=0
          for file in ${{ steps.modified_files.outputs.files }}; do
              if [[ $file == translation/dest/* ]]; then
                  echo "Error: $file was modified"
                  exit_code=1
              fi
          done
          if [ $exit_code -ne 0 ]; then
              echo "The files in translation/dest are automatically generated from Crowdin and should not be modified manually. Changes to these strings should be done at https://crowdin.com/project/lichess";
          fi
          exit $exit_code
